using MediatR;
using Microsoft.EntityFrameworkCore;
using QuotesApi.Data;

namespace QuotesApi.Queries;

public class GetQuotesQueryHandler
    : IRequestHandler<GetQuotesQuery, List<QuoteReadModel>>
{
    private readonly QuotesDbContext _db;

    public GetQuotesQueryHandler(
        QuotesDbContext db)
    {
        _db = db;
    }

    public async Task<List<QuoteReadModel>> Handle(
        GetQuotesQuery request,
        CancellationToken cancellationToken)
    {
        var query = _db.Quotes
            .AsNoTracking()
            .OrderBy(q => q.Id)
            .Skip((request.Page - 1) * request.Size)
            .Take(request.Size)
            .Select(q => new QuoteReadModel
            {
                Id = q.Id,
                Author = q.Author,
                Text = q.Text
            });

        // Display the SQL generated by EF Core
        Console.WriteLine("========== EF CORE SQL ==========");
        Console.WriteLine(query.ToQueryString());
        Console.WriteLine("=================================");

        return await query.ToListAsync(
            cancellationToken);
    }
}